# Generated by Django 5.2.1 on 2025-06-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='Last Name'),
        ),
    ]
