# Generated by Django 4.2.21 on 2025-05-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(error_messages={'unique': 'A status with that name already exists. Please choose another name.'}, max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
